### PR TITLE
Latest cloths

### PR DESCRIPTION
**Pull request by BlackRayquaza**

### CODE REVIEW

**Comment by Nightfirecat** [comment]
I'll test this a little later tonight. Preliminary report: switch your 4 spaces to tabs.

**Comment by Nightfirecat** [comment]
Besides the 4-space -> tabs, looks good. The image compression was a nice touch.

**Comment by BlackRayquaza** [comment]
@Nightfirecat [Before and after](http://imgur.com/kKLJW8d,TMPfEkP)

**Comment by Nightfirecat** [comment]
Yup, functionality looks good.

Just convert 4 spaces -> tabs, and I have no problem with this being merged. (@atomizer)

**Comment by atomizer** [comment]
alright

**Pull request merged**
