### PR TITLE
Add Kabam support

### PR DESCRIPTION
**Pull request by Zaltais333**
I just modify one line in order to connect with a Kabam account

### CODE REVIEW

**Comment by Nightfirecat** [comment]
Is there any difference in the Fiddler/network intercept steps than what's available on [the Steam oneclick setup](https://github.com/atomizer/muledump/wiki/Steam-Tutorial)? If so, I'd like to see a wiki page with documentation set up before implementing this.

If nothing else, I'll try to test this in the coming week or two and confirm/create documentation myself.

**Comment by Zaltais333** [comment]
I was initially using Fiddler to get my credential, but I manage to find the way kabam connect to the game. I put the procedure in a new wiki page.

**Comment by Nightfirecat** [comment]
I'm assuming this line should be corrected to read `Open your browser console while logged in on the game's page on Kabam's website`, or something along those lines? It should probably include a link to the game page as well. ([I assume it's this page when logged in?](https://www.kabam.com/games/realm-of-the-mad-god))

> Open your browser console while on the game's page **on Kongregate**

**Comment by Zaltais333** [comment]
Yes, indeed, I forgot to change this line.

**Comment by Nightfirecat** [comment]
:+1: :shipit:

**Comment by BlackRayquaza** [comment]
Totally forgot to do this myself..

**Comment by Nightfirecat** [comment]
Note: closes #58.

**Comment by atomizer** [comment]
Alright. Took the liberty to make code prettier.

**Comment by Nightfirecat** [comment]
:+1: for readability.

**Pull request merged**
